image: "maven" 



stages:
  - build
  - test

job 1 :
  stage : build
  script : mvn -Dskip.test=true package
  cache:
    key: ${CI_COMMIT_REF_SLUG-m2}
    paths:
    - ${HOME}/.m2/repository

  artifacts:
    name: "bob2"
    paths:
      - target/my-spark-app-1.0-SNAPSHOT.jar

job 2 :
  stage : test
  script: mvn verify