image: "maven" 



stages:
  - build
  - test
  - deploy

job 1 :
  stage : build
  script : mvn -DskipTests package
  cache:
    key: ${CI_COMMIT_REF_SLUG-m2}
    paths:
    - ${HOME}/.m2/repository

  artifacts:
    name: "bob2"
    paths:
      - target/*

job 2 :
  stage : test
  script: mvn verify

job 3 :
  stage: deploy
  script:
    - mvn site
    - mkdir .public
    - cp -r * target/site/* .public
    - mv .public public
    
  artifacts:
    paths:
      - public
  only:
    - master
